program: train.py
method: bayes
name: my_project_sweep
metric:
  goal: maximize
  name: valid_acc_epoch
parameters:
  batch_size: 
    values: [16,32,64]
  lr:
    min: 0.0001
    max: 0.1
  n_epochs:
    values: [5, 10, 15, 20]